# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Users/benji/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake

# The command to remove a file.
RM = /Users/benji/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/benji/Documents/Scripts/bfpmx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/benji/Documents/Scripts/bfpmx

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Users/benji/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/benji/Documents/Scripts/bfpmx/CMakeFiles /Users/benji/Documents/Scripts/bfpmx//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/benji/Documents/Scripts/bfpmx/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/benji/Documents/Scripts/bfpmx/CMakeFiles /Users/benji/Documents/Scripts/bfpmx//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/benji/Documents/Scripts/bfpmx/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bfpmx

# Build rule for target.
bfpmx: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bfpmx
.PHONY : bfpmx

# fast build rule for target.
bfpmx/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/build
.PHONY : bfpmx/fast

#=============================================================================
# Target rules for targets named test_main

# Build rule for target.
test_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_main
.PHONY : test_main

# fast build rule for target.
test_main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/build
.PHONY : test_main/fast

#=============================================================================
# Target rules for targets named test_marshal

# Build rule for target.
test_marshal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_marshal
.PHONY : test_marshal

# fast build rule for target.
test_marshal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_marshal.dir/build.make CMakeFiles/test_marshal.dir/build
.PHONY : test_marshal/fast

#=============================================================================
# Target rules for targets named test_playground

# Build rule for target.
test_playground: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_playground
.PHONY : test_playground

# fast build rule for target.
test_playground/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_playground.dir/build.make CMakeFiles/test_playground.dir/build
.PHONY : test_playground/fast

mx/arch/cpu/aarch64.o: mx/arch/cpu/aarch64.cpp.o
.PHONY : mx/arch/cpu/aarch64.o

# target to build an object file
mx/arch/cpu/aarch64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/arch/cpu/aarch64.cpp.o
.PHONY : mx/arch/cpu/aarch64.cpp.o

mx/arch/cpu/aarch64.i: mx/arch/cpu/aarch64.cpp.i
.PHONY : mx/arch/cpu/aarch64.i

# target to preprocess a source file
mx/arch/cpu/aarch64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/arch/cpu/aarch64.cpp.i
.PHONY : mx/arch/cpu/aarch64.cpp.i

mx/arch/cpu/aarch64.s: mx/arch/cpu/aarch64.cpp.s
.PHONY : mx/arch/cpu/aarch64.s

# target to generate assembly for a file
mx/arch/cpu/aarch64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/arch/cpu/aarch64.cpp.s
.PHONY : mx/arch/cpu/aarch64.cpp.s

mx/arch/cpu/x86_64.o: mx/arch/cpu/x86_64.cpp.o
.PHONY : mx/arch/cpu/x86_64.o

# target to build an object file
mx/arch/cpu/x86_64.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/arch/cpu/x86_64.cpp.o
.PHONY : mx/arch/cpu/x86_64.cpp.o

mx/arch/cpu/x86_64.i: mx/arch/cpu/x86_64.cpp.i
.PHONY : mx/arch/cpu/x86_64.i

# target to preprocess a source file
mx/arch/cpu/x86_64.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/arch/cpu/x86_64.cpp.i
.PHONY : mx/arch/cpu/x86_64.cpp.i

mx/arch/cpu/x86_64.s: mx/arch/cpu/x86_64.cpp.s
.PHONY : mx/arch/cpu/x86_64.s

# target to generate assembly for a file
mx/arch/cpu/x86_64.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/arch/cpu/x86_64.cpp.s
.PHONY : mx/arch/cpu/x86_64.cpp.s

mx/arch/gpu/CUDA.o: mx/arch/gpu/CUDA.cpp.o
.PHONY : mx/arch/gpu/CUDA.o

# target to build an object file
mx/arch/gpu/CUDA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/arch/gpu/CUDA.cpp.o
.PHONY : mx/arch/gpu/CUDA.cpp.o

mx/arch/gpu/CUDA.i: mx/arch/gpu/CUDA.cpp.i
.PHONY : mx/arch/gpu/CUDA.i

# target to preprocess a source file
mx/arch/gpu/CUDA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/arch/gpu/CUDA.cpp.i
.PHONY : mx/arch/gpu/CUDA.cpp.i

mx/arch/gpu/CUDA.s: mx/arch/gpu/CUDA.cpp.s
.PHONY : mx/arch/gpu/CUDA.s

# target to generate assembly for a file
mx/arch/gpu/CUDA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/arch/gpu/CUDA.cpp.s
.PHONY : mx/arch/gpu/CUDA.cpp.s

mx/definition/block_float/block/Block.o: mx/definition/block_float/block/Block.cpp.o
.PHONY : mx/definition/block_float/block/Block.o

# target to build an object file
mx/definition/block_float/block/Block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/definition/block_float/block/Block.cpp.o
.PHONY : mx/definition/block_float/block/Block.cpp.o

mx/definition/block_float/block/Block.i: mx/definition/block_float/block/Block.cpp.i
.PHONY : mx/definition/block_float/block/Block.i

# target to preprocess a source file
mx/definition/block_float/block/Block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/definition/block_float/block/Block.cpp.i
.PHONY : mx/definition/block_float/block/Block.cpp.i

mx/definition/block_float/block/Block.s: mx/definition/block_float/block/Block.cpp.s
.PHONY : mx/definition/block_float/block/Block.s

# target to generate assembly for a file
mx/definition/block_float/block/Block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/definition/block_float/block/Block.cpp.s
.PHONY : mx/definition/block_float/block/Block.cpp.s

mx/definition/block_float/factory/BlockFactory.o: mx/definition/block_float/factory/BlockFactory.cpp.o
.PHONY : mx/definition/block_float/factory/BlockFactory.o

# target to build an object file
mx/definition/block_float/factory/BlockFactory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/definition/block_float/factory/BlockFactory.cpp.o
.PHONY : mx/definition/block_float/factory/BlockFactory.cpp.o

mx/definition/block_float/factory/BlockFactory.i: mx/definition/block_float/factory/BlockFactory.cpp.i
.PHONY : mx/definition/block_float/factory/BlockFactory.i

# target to preprocess a source file
mx/definition/block_float/factory/BlockFactory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/definition/block_float/factory/BlockFactory.cpp.i
.PHONY : mx/definition/block_float/factory/BlockFactory.cpp.i

mx/definition/block_float/factory/BlockFactory.s: mx/definition/block_float/factory/BlockFactory.cpp.s
.PHONY : mx/definition/block_float/factory/BlockFactory.s

# target to generate assembly for a file
mx/definition/block_float/factory/BlockFactory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/definition/block_float/factory/BlockFactory.cpp.s
.PHONY : mx/definition/block_float/factory/BlockFactory.cpp.s

mx/definition/block_float/repr/FloatRepr.o: mx/definition/block_float/repr/FloatRepr.cpp.o
.PHONY : mx/definition/block_float/repr/FloatRepr.o

# target to build an object file
mx/definition/block_float/repr/FloatRepr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/definition/block_float/repr/FloatRepr.cpp.o
.PHONY : mx/definition/block_float/repr/FloatRepr.cpp.o

mx/definition/block_float/repr/FloatRepr.i: mx/definition/block_float/repr/FloatRepr.cpp.i
.PHONY : mx/definition/block_float/repr/FloatRepr.i

# target to preprocess a source file
mx/definition/block_float/repr/FloatRepr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/definition/block_float/repr/FloatRepr.cpp.i
.PHONY : mx/definition/block_float/repr/FloatRepr.cpp.i

mx/definition/block_float/repr/FloatRepr.s: mx/definition/block_float/repr/FloatRepr.cpp.s
.PHONY : mx/definition/block_float/repr/FloatRepr.s

# target to generate assembly for a file
mx/definition/block_float/repr/FloatRepr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bfpmx.dir/build.make CMakeFiles/bfpmx.dir/mx/definition/block_float/repr/FloatRepr.cpp.s
.PHONY : mx/definition/block_float/repr/FloatRepr.cpp.s

test/main.o: test/main.cpp.o
.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i
.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s
.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_main.dir/build.make CMakeFiles/test_main.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

test/marshalling.o: test/marshalling.cpp.o
.PHONY : test/marshalling.o

# target to build an object file
test/marshalling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_marshal.dir/build.make CMakeFiles/test_marshal.dir/test/marshalling.cpp.o
.PHONY : test/marshalling.cpp.o

test/marshalling.i: test/marshalling.cpp.i
.PHONY : test/marshalling.i

# target to preprocess a source file
test/marshalling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_marshal.dir/build.make CMakeFiles/test_marshal.dir/test/marshalling.cpp.i
.PHONY : test/marshalling.cpp.i

test/marshalling.s: test/marshalling.cpp.s
.PHONY : test/marshalling.s

# target to generate assembly for a file
test/marshalling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_marshal.dir/build.make CMakeFiles/test_marshal.dir/test/marshalling.cpp.s
.PHONY : test/marshalling.cpp.s

test/playground.o: test/playground.cpp.o
.PHONY : test/playground.o

# target to build an object file
test/playground.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_playground.dir/build.make CMakeFiles/test_playground.dir/test/playground.cpp.o
.PHONY : test/playground.cpp.o

test/playground.i: test/playground.cpp.i
.PHONY : test/playground.i

# target to preprocess a source file
test/playground.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_playground.dir/build.make CMakeFiles/test_playground.dir/test/playground.cpp.i
.PHONY : test/playground.cpp.i

test/playground.s: test/playground.cpp.s
.PHONY : test/playground.s

# target to generate assembly for a file
test/playground.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_playground.dir/build.make CMakeFiles/test_playground.dir/test/playground.cpp.s
.PHONY : test/playground.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... bfpmx"
	@echo "... test_main"
	@echo "... test_marshal"
	@echo "... test_playground"
	@echo "... mx/arch/cpu/aarch64.o"
	@echo "... mx/arch/cpu/aarch64.i"
	@echo "... mx/arch/cpu/aarch64.s"
	@echo "... mx/arch/cpu/x86_64.o"
	@echo "... mx/arch/cpu/x86_64.i"
	@echo "... mx/arch/cpu/x86_64.s"
	@echo "... mx/arch/gpu/CUDA.o"
	@echo "... mx/arch/gpu/CUDA.i"
	@echo "... mx/arch/gpu/CUDA.s"
	@echo "... mx/definition/block_float/block/Block.o"
	@echo "... mx/definition/block_float/block/Block.i"
	@echo "... mx/definition/block_float/block/Block.s"
	@echo "... mx/definition/block_float/factory/BlockFactory.o"
	@echo "... mx/definition/block_float/factory/BlockFactory.i"
	@echo "... mx/definition/block_float/factory/BlockFactory.s"
	@echo "... mx/definition/block_float/repr/FloatRepr.o"
	@echo "... mx/definition/block_float/repr/FloatRepr.i"
	@echo "... mx/definition/block_float/repr/FloatRepr.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
	@echo "... test/marshalling.o"
	@echo "... test/marshalling.i"
	@echo "... test/marshalling.s"
	@echo "... test/playground.o"
	@echo "... test/playground.i"
	@echo "... test/playground.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

